#home automation stack
version: "3.7"
services:

  homeassistant:
    container_name: homeassistant
    restart: unless-stopped
    image: homeassistant/home-assistant:latest
    depends_on:
      - mqtt
    devices:
      - /dev/ttyUSB0:/dev/ttyUSB0
      - /dev/ttyUSB1:/dev/ttyUSB1
      - /dev/ttyACM0:/dev/ttyACM0
    volumes:
      - ${USERDIR}/stacks/homeautomation/homeassistant:/config
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 8123:8123
    privileged: true
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - SERVER_IP=${SERVER_IP}
      - DOMAINNAME=${DOMAINNAME}
      - DB_CONNECTION=mysql://${MYSQL_USER}:${MYSQL_USER_PASSWORD}@mariadb/${HA_DATABASE}?charset=utf8
    network_mode: host
    labels:
      - com.centurylinklabs.watchtower.enable=true

      #- traefik.enable=true
      #- traefik.backend=homeassistant
      #- traefik.frontend.rule=Host:homeassistant.${DOMAINNAME}
      #- traefik.port=8123
      #- traefik.docker.network=traefik_proxy
      #- traefik.frontend.headers.SSLRedirect=true
      #- traefik.frontend.headers.STSSeconds=315360000
      #- traefik.frontend.headers.browserXSSFilter=true
      #- traefik.frontend.headers.contentTypeNosniff=true
      #- traefik.frontend.headers.forceSTSHeader=true
      #- traefik.frontend.headers.SSLHost=${DOMAINNAME}
      #- traefik.frontend.headers.STSIncludeSubdomains=true
      #- traefik.frontend.headers.STSPreload=true
      #- traefik.frontend.headers.frameDeny=true


  esphome:
    container_name: esphome
    image: esphome/esphome
    devices:
      - /dev/ttyUSB0:/dev/ttyUSB0
      - /dev/ttyUSB1:/dev/ttyUSB1
    privileged: true
    ports:
      - 6052:6052
    volumes:
      - ${USERDIR}/stacks/homeautomation/esphome:/config:rw
    #command: esphome
    network_mode: host
    restart: unless-stopped
    
  mqtt:
    image: eclipse-mosquitto:latest #1.5.8
    container_name: eclipse-mqtt
    restart: unless-stopped
    ports:
      - 1883:1883
      - 1884:1884
      - 9000:9000
      - 9001:9001
    volumes:
      - ${USERDIR}/stacks/homeautomation/mqtt/config:/mosquitto/config
      - ${USERDIR}/stacks/homeautomation/mqtt/data:/mosquitto/data
      - ${USERDIR}/stacks/homeautomation/mqtt/log:/mosquitto/log
      
  mqttdashboard:
    image: darkdirk/mqttdashboard
    container_name: mqttdashboard
    depends_on:
      - mqtt
    restart: unless-stopped
    networks:
      - default
      - traefik_proxy
    environment:
      - user=admin
      - password=admin
    ports:
      - 6868:80
    labels:
      - traefik.frontend.rule=Host:mqtt.${DOMAINNAME}
      - traefik.enable=true
      - traefik.frontend.headers.SSLRedirect=true



  # monitor:
  #   container_name: monitorNUC
  #   image: mashupmill/presence-monitor:latest
  #   network_mode: host
  #   privileged: true
  #   restart: unless-stopped
  #   depends_on:
  #     - mqtt
  #   environment:
  #     MQTT_ADDRESS: ${SERVER_IP}
  #     MQTT_USER: mqtt
  #     MQTT_PASSWORD: mqtt1968!
  #     MQTT_PUBLISHER_IDENTITY: intelNUC
  #     # - MQTT_TOPICPATH=monitor
  #     # - MQTT_PORT=1883
  #     # - MQTT_VERSION=eclipse-mosquitto
  #     # - MQTT_CERTIFICATE_PATH='/config'
  #     # - PREF_ARRIVAL_SCAN_ATTEMPTS=1
  #     # - PREF_DEPART_SCAN_ATTEMPTS=2
  #     # - PREF_BEACON_EXPIRATION=240
  #     # - PREF_MINIMUM_TIME_BETWEEN_SCANS=15
  #     # - PREF_PASS_FILTER_ADV_FLAGS_ARRIVE=".*"
  #     # - PREF_PASS_FILTER_MANUFACTURER_ARRIVE=".*"
  #     # - PREF_FAIL_FILTER_ADV_FLAGS_ARRIVE="NONE"
  #     # - PREF_FAIL_FILTER_MANUFACTURER_ARRIVE="NONE"
  #     # KNOWN_BEACON_ADDRESSES: |
  #     #   FF:FF:FF:FF:FF:FF Red Tag
  #     #   FF:FF:FF:FF:FF:FF Green Tag
  #     KNOWN_STATIC_ADDRESSES: |
  #       88:AE:07:79:63:A0 Mike_iPad
  #       90:E1:7B:15:32:29 Mike_iPhone_XS
  #     ######- KNOWN_STATIC_ADDRESSES=88:AE:07:79:63:A0 Mike_iPad
  #   command: ['-b']
  #   volumes:
  #     - /opt/bluetooth:/var/lib/bluetooth    
  #     - ${USERDIR}/stacks/homeautomation/monitor/config:/config
  #     - /etc/localtime:/etc/localtime:ro
    

networks:
  traefik_proxy:
    external:
      name: traefik_proxy
  default:
    driver: bridge
