#media stack
version: "3.7"
services:

  airvideohd:
    container_name: airvideohd
    image: bondesen/airvideohd:latest
    restart: unless-stopped
    ports:
      - 5353:5353/udp
      - 45633:45633/tcp
      - 45633:45633/udp
    network_mode: host
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
    volumes:
      - ${USERDIR}/stacks/media/airvideohd:/config 
      - ${USERDIR}/nas:/media
      - ${USERDIR}/nas/temp/airvideohd_transcode:/transcode
      
  # https://www.reddit.com/r/PleX/comments/ai9xyw/plex_running_in_docker_cant_find_server/eenf61e/
  plexms:
    container_name: plexms
    restart: unless-stopped
    image:  plexinc/pms-docker:latest #1.14.1.5488-cc260c476
    #image:  linuxserver/plex:1.15.2.793-782228f99-ls13
    volumes:
      - ${USERDIR}/stacks/media/plexms/config:/config
      - ${USERDIR}/stacks/media/plexms/media:/media
      - ${USERDIR}/nas/movies:/movies
      - ${USERDIR}/nas/tv:/tv
    #  - ${USERDIR}/nas/downloads:/downloads
      - ${USERDIR}/nas/videos:/videos
      - ${USERDIR}/nas/manual:/manual
      - ${USERDIR}/nas/temp/plex_transcode:/transcode
    ports:
      - 32400:32400/tcp
      - 33400:33400/tcp
      - 3005:3005/tcp
      - 8324:8324/tcp
      - 32469:32469/tcp
      - 1900:1900/udp
      - 32410:32410/udp
      - 32412:32412/udp
      - 32413:32413/udp
      - 32414:32414/udp
    environment:
      - TZ=${TZ}
      - HOSTNAME='Docker Plex'
      - PLEX_UID=${PUID}
      - PLEX_GID=${PGID}
      - ADVERTISE_IP='http://${SERVER-IP}:32400/'
    networks:
      - traefik_proxy
#      - default
    labels:
      - traefik.frontend.rule=Host:plex.${DOMAINNAME}
      - traefik.enable=true
      - traefik.frontend.headers.SSLRedirect=true
      - traefik.port=32400
      
  qbittorrent:
    image: linuxserver/qbittorrent:latest
    container_name: qbittorrent
    networks:
      - traefik_proxy
    volumes:
      - ${USERDIR}/stacks/media/qbittorrent:/config
      - ${USERDIR}/nas/downloads:/downloads
    ports:
      - 8085:8085
      - 6881:6881
      - 6881:6881/udp
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - UMASK_SET=002
      - WEBUI_PORT=8085
    labels:
      - traefik.frontend.rule=Host:qbittorrent.${DOMAINNAME}
      - traefik.enable=true
      - traefik.frontend.headers.SSLRedirect=true
      - traefik.port=8085
      
  sonarr:
    container_name: sonarr
    image: linuxserver/sonarr:latest
    restart: unless-stopped
    depends_on:
      - jackett
    environment:
      - TZ=${TZ}
      - PUID=${PUID}
      - PGID=${PGID}
    ports:
      - 8989:8989
    networks:
      - traefik_proxy
    volumes:
      - ${USERDIR}/stacks/media/sonarr:/config
      - ${USERDIR}/nas/tv:/tv
      - ${USERDIR}/nas/downloads:/downloads
    labels:
      - traefik.frontend.rule=Host:sonarr.${DOMAINNAME}
      - traefik.enable=true
      - traefik.frontend.headers.SSLRedirect=true

  radarr:
    container_name: radarr
    image: linuxserver/radarr:latest
    restart: unless-stopped
    depends_on:
      - jackett
    ports:
      - 7878:7878
    environment:
      - TZ=${TZ}
      - PUID=${PUID}
      - PGID=${PGID}
    networks:
      - traefik_proxy
    volumes:
      - ${USERDIR}/stacks/media/radarr:/config
      - ${USERDIR}/nas/downloads:/downloads
      - ${USERDIR}/nas/movies:/movies
    labels:
      - traefik.frontend.rule=Host:radarr.${DOMAINNAME}
      - traefik.enable=true
      - traefik.frontend.headers.SSLRedirect=true

  lazylibrarian:
    image: linuxserver/lazylibrarian:latest
    container_name: lazylibrarian
    environment:
      - PUID=1001
      - PGID=1001
      - TZ=Europe/London
    networks:
      - traefik_proxy
    volumes:
      - ${USERDIR}/stacks/media/lazylibrarian:/config
      - ${USERDIR}/stacks/media/storage/downloads:/downloads
      - ${USERDIR}/stacks/media/storage/books:/books
    ports:
      - 5299:5299
    restart: unless-stopped
    labels:
      - traefik.frontend.rule=Host:lazylibrarian.${DOMAINNAME}
      - traefik.enable=true
      - traefik.frontend.headers.SSLRedirect=true
      
  jackett:
    image: linuxserver/jackett:latest #amd64-v0.11.15-ls14
    container_name: jackett
    restart: unless-stopped
    environment:
      - PGID=1000
      - PUID=1000
      - TZ=${TZ}
    networks:
      - traefik_proxy
    volumes:
      - ${USERDIR}/stacks/media/jackett/config:/config
      - ${USERDIR}/nas/downloads:/downloads
    ports:
      - 9117:9117
    labels:
      - traefik.frontend.rule=Host:jackett.${DOMAINNAME}
      - traefik.enable=true
      - traefik.frontend.headers.SSLRedirect=true

networks:
  traefik_proxy:
    external:
      name: traefik_proxy
  default:
    driver: bridge
