[entryPoints]
  [entryPoints.http]
  address = ":80"
  [entryPoints.http.redirect]
    entryPoint = "https"
  [entryPoints.https]
  address = ":443"
  
[backends]

  [backends.backend-esphome]
    [backends.backend-esphome.servers]
      [backends.backend-esphome.servers.server-homeassistant-ext]
      url = "http://192.168.7.62:6052"
      weight = 4
      
  [backends.backend-homeassistant]
    [backends.backend-homeassistant.servers]
      [backends.backend-homeassistant.servers.server-homeassistant-ext]
      url = "http://192.168.7.62:8123"
      weight = 2

[frontends]

  [frontends.frontend-esphome]
  backend = "backend-esphome"
  passHostHeader = true
  InsecureSkipVerify = true
  [frontends.frontend-esphome.routes]
    [frontends.frontend-esphome.routes.route-esphome-ext]
    rule = "Host:esphome.suttondr.net"

  [frontends.frontend-homeassistant]
  backend = "backend-homeassistant"
  passHostHeader = true
  InsecureSkipVerify = true
  [frontends.frontend-homeassistant.routes]
    [frontends.frontend-homeassistant.routes.route-homeassistant-ext]
    rule = "Host:homeassistant.suttondr.net"

  
