#Latest: {{states('sensor.latest_version')}}
#Current: {{states('sensor.current_version')}}


- platform: template
  sensors:

    system_ready:
      friendly_name: "System ready"
      value_template: "{{ is_state('input_boolean.system_ready', 'on') }}"
      device_class: moving
      
# - platform: trend
#   sensors:
#     bathroom_humidity_rising:
#       entity_id: sensor.mba_humidity
