#cover: !include covers.yaml
- platform: myq
  username: !secret myq_username
  password: !secret myq_password
  type: liftmaster


- platform: template
  covers:
    google_frontdoor:
    # friendly_name: 
      value_template: "{{ is_state('lock.front_door_lock', 'locked') }}"
      open_cover:
        service: lock.unlock
        data:
          entity_id: lock.front_door_lock
      close_cover:
        service: lock.lock
        data:
          entity_id: lock.front_door_lock
    google_garagedoor:
      value_template: "{{ is_state('cover.garage_door_opener', 'closed') }}"
      open_cover:
        service: cover.open_cover
        data:
          entity_id: cover.garage_door_opener
      close_cover:
        service: cover.close_cover
        data:
          entity_id: cover.garage_door_opener
