- platform: universal
  name: google_media_devices
  children:
    - media_player.bathroom_speaker
    - media_player.entryway_speaker
    - media_player.living_room_speaker
    - media_player.bedroom_speaker
    - media_player.den_speaker
