esphome:
  name: car_hyundai
  platform: ESP8266
  board: d1_mini

wifi:
  ssid: "SoftKittyWarmKitty"
  password: "68ecececec"
  fast_connect: true
  use_address: 172.16.68.120
  reboot_timeout: 0s
  
  manual_ip:
    static_ip: 172.16.68.120
    gateway: 172.16.68.1
    subnet: 255.255.255.0

mqtt:
  discovery: true
  discovery_prefix: homeassistant
  client_id: home-assistant-esphome-hyundai
  broker: 172.16.68.62
  username: mqtt
  password: mqtt1968!
  reboot_timeout: 0s
  keepalive: 2s
    
logger:

ota:
  password: 'spooey'

binary_sensor:
  - platform: status
    name: "Garage Opened HYUNDAI"
    id: garage_opened_hyundai

sensor:
  - platform: template
    name: "HYUNDAI"
    lambda: |-
    
      static int num_cycles = 0;
      static int prev_count = 0;
      int retVal;
      num_cycles += 1;
      bool ha_responded = (id(garage_opened_hyundai).state); // Home Assistant set binary_sensor ON
      if (ha_responded) {
        retVal = prev_count;
      }
      else
      {
        retVal = num_cycles;
        prev_count = num_cycles;
      }
      return retVal;
    
    update_interval: 1000ms
    