- alias: Garage Opened
  hide_entity: True
  trigger:
    - platform: state
      entity_id: cover.garage_door_opener
      to: 'open'
  condition:
    - condition: state
      entity_id: input_boolean.autolock
      state: 'on'
  action:
    - service: timer.start
      entity_id: timer.garage_door
    - service: notify.notify
      data:
        title: "Garage"
        message: "Opened"
      
- alias: Garage Closed
  hide_entity: True
  trigger:
    - platform: state
      entity_id: cover.garage_door_opener
      to: 'closed'
  action:
    - service: timer.cancel
      entity_id:  timer.garage_door
    - service: notify.notify
      data:
        title: "Garage"
        message: "Closed"
      
- alias: Garage Opened Timer Finished
  hide_entity: True
  trigger:
    - platform: event
      event_type: timer.finished
      event_data:
        entity_id: timer.garage_door
  condition:
    - condition: state
      entity_id: cover.garage_door_opener
      state: 'open'
    - condition: state
      entity_id: input_boolean.autolock
      state: 'on'
  action:
    - service: ifttt.trigger
      data: {"event": "GarageLeftOpened"}
    - service: timer.start
      entity_id: timer.garage_door
