- alias: MBA Humidity Rising
  trigger:
    platform: state
    entity_id: binary_sensor.bathroom_humidity_rising
    from: 'off'
    to: 'on'
  action:
    - service: switch.turn_on
      entity_id: switch.homeseer_switch_mba_fan

- alias: MBA Fan Auto Off
  trigger: 
    entity_id: switch.homeseer_switch_mba_fan
    platform: state
    to: 'on'
    for:
      minutes: 30
  action:
    - service: switch.turn_off
      entity_id: switch.homeseer_switch_mba_fan

- alias: MBA Fan Humidity Drop
  trigger: 
    platform: state
    entity_id: binary_sensor.humidity_level_returned
    to: 'on'
  action:
    - service: switch.turn_off
      entity_id: switch.homeseer_switch_mba_fan

- alias: Save Humidity State
  trigger:
    platform: time_pattern
    minutes: '/5'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: switch.homeseer_switch_mba_fan
        state: 'off'
  action:
    - service: input_text.set_value
      data_template:
        entity_id: input_text.save_mba_humidity
        value: "{{states('sensor.mba_humidity') | string }}"